version: '3.9'
services:
  web:
    build: .
    container_name: rebase_labs
    command: bash -c "ruby server.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - gems-labs:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - sidekiq
    networks:
      - medical-center

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - medical-center
  
  redis:
    image: redis:7.2-rc3
    container_name: redis
    networks:
      - medical-center

  sidekiq:
    build: .
    container_name: sidekiq
    command: bash -c "bundle exec sidekiq -r ./lib/csv_importer_worker.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - gems-labs:/usr/local/bundle
    depends_on:
      - redis
    networks:
      - medical-center

networks:
  medical-center:

volumes:
  postgres_data:
  gems-labs:
