source 'https://rubygems.org'

gem 'activerecord', '~> 7.0'
gem 'activerecord-import', '~> 1.4'
gem 'json', '~> 2.6'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.3'
gem 'rack', '~> 2.2.4'
gem 'rack-test', '~> 2.1'
gem 'rake', '~> 13.0'
gem 'sinatra', '~> 3.0'
gem 'sinatra-activerecord', '~> 2.0'
